Basic TCP handler
pbzweihander/an2linuxserver-rs pull request #1
Opened 2021-02-21 17:32 UTC by skystar-p

Implemented:
* Pairing handler
  * `authorized_certs` parsing, storing
  * cert fingerprinting
* Notification handler
  * message parsing
  * custom client cert verifier (wow, this was very painful)

2021-02-21 18:12 UTC, pbzweihander requested changes
아직 다 보진 않았지만 일단 요정도 리뷰

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +    config: Option<Config>,
음 저는 ConfigManager가 Config까지 들고있지 않기를 바랬어요

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +    config: Option<Config>,
ConfigManager는 config file path만 뱉고 Config이 필요하면 get_or_create_config으로 불러와서 따로 들고있는게 낫지 않을까요

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +    fn from_file(path: PathBuf) -> Result<AuthorizedCerts> {
```suggestion
    fn from_path(path: &Path) -> Result<AuthorizedCerts> {
```

from_path가 더 맞는 표현인 것 같아요. 그리고 이건 체크해보진 않았는데 &Path만 받아도 된다면 owned 타입인 PathBuf보다 &Path가 나을거에요

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +    fn from_file(path: PathBuf) -> Result<AuthorizedCerts> {
```suggestion
    fn from_file(path: PathBuf) -> Result<Self> {
```

아 글고 중요한건 아닌데 타입을 Self로 적으면 보기에도 편하고 나중에 혹시 리팩토링할 때도 편해진답니다

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +        f.read_to_string(&mut buf)?;
from_file이 하는 일이 좀 많은 것 같은데 아예 정말 File만 받아서 읽게만 하거나 impl Read만 받게 하거나 그냥 String을 받게 하는게 어때요?

2021-02-21 18:12 UTC, pbzweihander commented on src/config.rs
> +        for line in buf.lines() {
좀 더 최적화하자면 File을 BufReader로 감싸서 BufReader에서 직접 lines로 한 줄씩만 읽게 하는 것도 가능합니다

2021-02-21 18:12 UTC, pbzweihander commented on src/tcp.rs
> +    for stream in listener.incoming() {
이건 스펙을 다시 생각해봐야하는 문제이긴 한데 이렇게 구현하면

1. async 하지 않음
2. 블루투스 리스너랑 동시에 못 씀

같은 문제가 있어요. 1은 그냥 synchronous하게 해도 될 것 같기도 한데 2는 그래도 되는지 고민 필요

2021-02-21 18:12 UTC, pbzweihander commented on src/tls.rs
> +pub fn make_tls_server_config_no_client_auth(
으음 make_tls_server_config_no_client_auth 이랑 make_tls_server_config_with_auth 가 둘 다 있을거면 차라리 builder 패턴을 쓰는게 나을 것 같아요.

TlsInfoBuilder 같은 struct가 있고, `TlsInfoBuilder::new(server_certs, privkey).build()?` 하면 without client auth가 되고 `TlsInfoBuilder::new(server_certs, privkey).with_client_certs(client_certs).build()?` 하면 with auth가 되는 식으로요

2021-02-21 18:38 UTC, pbzweihander commented on src/config.rs
> +fn get_bool_coerce(ini: &Ini, section: &str, key: &str) -> Result<Option<bool>> {
요거는 configparser에 PR을 날려서 수정해도 될 것 같기도..

2021-02-22 01:07 UTC, skystar-p commented on src/tcp.rs
> +    for stream in listener.incoming() {
우선 pairing은 `./an2linuxserver_rs pair` 커맨드로 1회성으로 끝나는 애라서 1번은 딱히 상관 없을 것 같고... 아마 pairing을 1회성 커맨드로 다시 만든다고 하면 `./an2linuxserver_rs pair --bluetooth` 이런 식으로 받게 해두면 되지 않을까 싶기도 하고?

2021-02-22 01:32 UTC, skystar-p commented on src/tls.rs
> +pub fn make_tls_server_config_no_client_auth(
9d1021d

2021-02-22 01:39 UTC, skystar-p commented on src/config.rs
> +    fn from_file(path: PathBuf) -> Result<AuthorizedCerts> {
8b076fd

2021-02-22 01:40 UTC, skystar-p commented on src/config.rs
> +    config: Option<Config>,
근데 각종 Path들 (e.g. authorized_certs path 등등)에 대한 메서드를 저 친구가 들고 있어서... config로만은 부족해서 저렇게 리팩토링 해놨던 것인데.. 더 좋은 방법이 있을까나요

2021-02-22 01:46 UTC, skystar-p commented on src/config.rs
> +        for line in buf.lines() {
이 함수 자체가 파일 전체를 다 한번에 읽는 거라 BufReader의 최적화 성능을 기대할 수 없을 것 같은데 잘못 이해한건가요?

2021-02-22 02:16 UTC, skystar-p commented on src/config.rs
> +        f.read_to_string(&mut buf)?;
이걸 원한 것인진 잘 모르겠지만...! 수정사항 3505608

2021-02-22 02:22 UTC, skystar-p commented on src/config.rs
> +fn get_bool_coerce(ini: &Ini, section: &str, key: &str) -> Result<Option<bool>> {
PR은 날리되 일단 급한대로 땜빵해서 쓰는 것으로...

2021-02-22 07:30 UTC, skystar-p commented on src/config.rs
> +fn get_bool_coerce(ini: &Ini, section: &str, key: &str) -> Result<Option<bool>> {
https://github.com/mexili/configparser-rs/pull/12 로 머지는 되었으니 나중에 릴리즈 되었을 때 쓰면 될듯

2021-02-22 11:18 UTC, pbzweihander commented on src/tcp.rs
> +    for stream in listener.incoming() {
아 이 함수는 페어링 리스너라서 맞네요 사실 아래 노티피케이션 핸들러 함수에서 하고 싶은 말이었어요

2021-02-22 11:19 UTC, pbzweihander commented on src/tls.rs
> +    pub fn build_tls_info(self) -> Result<TlsInfo> {
TlsInfoBuilder 라는 이름에서 tls info를 만든다는 뜻이 있어서 build 라고만 해도 될거 같긴 해요

2021-02-22 11:21 UTC, pbzweihander commented on src/config.rs
> +    pub fn add_authorized_cert(&self, cert_der: &dyn AsRef<[u8]>) -> Result<()> {
(진짜 사소한거긴 한데) 다른 메서드랑 통일성을 맞춰서 parse_가 아니고 get_으로 시작해도 되었을 거 같아요

2021-02-22 11:22 UTC, pbzweihander commented on src/config.rs
> +    pub fn parse_authorized_cert(&self) -> Result<AuthorizedCerts> {
(진짜 사소한거긴 한데) 다른 메서드랑 통일성을 맞춰서 parse_가 아니고 get_으로 시작해도 되었을 거 같아요

2021-02-22 11:30 UTC, pbzweihander commented on src/config.rs
> +    config: Option<Config>,
으으으음... 도메인별로 아예 분리했으면 좋겠는데.. 아예 TlsManager 같은 struct가 있고 거기서 add_authorized_certs 같은 메서드를 구현하고 그 친구만 들고있으면 되게 한다던지?

이건 제가 나중에 리팩토링하면서 생각해볼게요. 일단 구현 상에 문제는 없을 듯

2021-02-22 11:31 UTC, pbzweihander commented on src/config.rs
> +        for line in buf.lines() {
지금은 str 받게 하셔서 상관 없긴 한데 파일을 처음부터 끝까지 읽고 다시 lines로 쪼개서 보면 두 번 iterate하는 거니까 BufReader로 라인 단위로 읽으면서 처리하면 한 번 iterate하면 되니까요

2021-02-22 11:32 UTC, skystar-p commented on src/config.rs
> +        for line in buf.lines() {
흠, read() 시스템 콜 여러 번 날리진 않나요? BufReader가 그런 용도로 알고 있는데.. 그럴거면 첨부터 쭉 다 읽는게 훨씬 빠를지도? (메모리는 좀 더 씀)

2021-02-22 12:08 UTC, skystar-p commented on src/tcp.rs
> +    for stream in listener.incoming() {
그건 아마 저 각각의 listener을 따로 async 하게 띄워야할 것 같네요. 1은 성능 개선이고, 2는 스펙 충족을 위해 반드시 해야 하는 것이니 우선은 2번을 구현하는 걸 목표로 하고, 블루투스 핸들러를 만들 때 넣어도 괜찮을 거 같아요

2021-02-22 12:08 UTC, pbzweihander commented on src/tcp.rs
> +    for stream in listener.incoming() {
죠습니다

2021-02-22 12:09 UTC, pbzweihander commented on src/config.rs
> +        for line in buf.lines() {
그릏네요 아무튼 사소한거긴 해요

2021-02-22 12:16 UTC, pbzweihander approved these changes

2021-02-22 12:16 UTC, pbzweihander commented
나머지 네이밍 이슈 등은 어차피 한번 구현 끝나고 리팩토링을 해야해서 그 때 한꺼번에 하고, 동작 관련해서는 큰 문제 없어보여서 일단 머지할게요

2021-02-22 12:16 UTC, merged